armcc -Otime -c ch07test.c
armasm -cpu 5TE bits.s
armasm -cpu 5TE div_a7m.s
armasm -cpu 5TE div_a9e.s
armcc -Otime -c gen.c
armasm -cpu 5TE mul.s
armasm -cpu 5TE norm.s
armasm -cpu 5TE rand.s
armcc -Otime -c ref_bits.c
armcc -Otime -c ref_div.c
armcc -Otime -c ref_mul.c
armcc -Otime -c ref_norm.c
armcc -Otime -c ref_root.c
armcc -Otime -c ref_sat.c
armcc -Otime -c ref_tran.c
armasm -cpu 5TE root.s
armasm -cpu 5TE sat.s
armasm -cpu 5TE tran.s
armlink -o ch07test.axf ch07test.o bits.o div_a7m.o div_a9e.o gen.o mul.o norm.o rand.o ref_bits.o ref_div.o ref_mul.o ref_norm.o ref_root.o ref_sat.o ref_tran.o root.o sat.o tran.o
