#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias e='emacsclient --no-wait --alternate-editor=emacs'
alias ee='emacs -nw -Q --load ~/.emacs.d/short_init.el'
#LANG=zh_CN.UTF-8
